CREATE TABLE Pairs 
(
ID INT IDENTITY (1,1) PRIMARY KEY,
User1ID INT NOT NULL,
User2ID INT NOT NULL,
User1Decision VARCHAR(10) NOT NULL,
User2Decision VARCHAR(10) NULL,
MatchDate DATETIME2,

CONSTRAINT fk_user1 FOREIGN KEY (user1ID) REFERENCES users (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT fk_user2 FOREIGN KEY (user2ID) REFERENCES users (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
)
