CREATE TABLE UsersInterests
(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	UserID INT NOT NULL,
	InterestID INT NOT NULL,

	CONSTRAINT fk1_user FOREIGN KEY (UserID) REFERENCES users (ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk2_interest FOREIGN KEY (InterestID) REFERENCES interests (ID) ON DELETE CASCADE ON UPDATE CASCADE
)
