CREATE TABLE Users
(
ID INT IDENTITY (1,1) PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
Email VARCHAR(255) NOT NULL,
Password VARCHAR(255) NOT NULL,
Gender VARCHAR(10) NOT NULL,
Photo VARBINARY(MAX) NOT NULL,
InterestedM VARCHAR(10) NOT NULL,
InterestedF VARCHAR(10) NOT NULL,
LastActive DATETIME2 NOT NULL,
AboutMe VARCHAR(255),
MinAgePreference INT NOT NULL,
MaxAgePreference INT NOT NULL,
Birthday DATETIME2 NOT NULL,
UNIQUE(Email)
)